"""Update entity model

Revision ID: 5d3328133717
Revises: 7395869d33e5
Create Date: 2025-07-06 17:44:31.741933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3328133717'
down_revision: Union[str, Sequence[str], None] = '7395869d33e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('ogrn', sa.String(), nullable=True))
    op.add_column('entities', sa.Column('address', sa.String(), nullable=True))
    op.add_column('entities', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('entities', sa.Column('risk_summary', sa.String(), nullable=True))
    op.add_column('entities', sa.Column('source', sa.String(), nullable=True))
    op.add_column('entities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'updated_at')
    op.drop_column('entities', 'source')
    op.drop_column('entities', 'risk_summary')
    op.drop_column('entities', 'risk_level')
    op.drop_column('entities', 'address')
    op.drop_column('entities', 'ogrn')
    # ### end Alembic commands ###
